[2024-07-19T18:13:18.423+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-19T18:13:19.095+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.md_currency_d manual__2024-07-19T18:13:05.641856+00:00 [queued]>
[2024-07-19T18:13:19.347+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.md_currency_d manual__2024-07-19T18:13:05.641856+00:00 [queued]>
[2024-07-19T18:13:19.348+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-07-19T18:13:19.467+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): md_currency_d> on 2024-07-19 18:13:05.641856+00:00
[2024-07-19T18:13:19.521+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=3825) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-19T18:13:19.536+0000] {standard_task_runner.py:64} INFO - Started process 3843 to run task
[2024-07-19T18:13:19.542+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'md_currency_d', 'manual__2024-07-19T18:13:05.641856+00:00', '--job-id', '368', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmp9jxx3cbu']
[2024-07-19T18:13:19.548+0000] {standard_task_runner.py:91} INFO - Job 368: Subtask md_currency_d
[2024-07-19T18:13:19.887+0000] {task_command.py:426} INFO - Running <TaskInstance: insert_data.md_currency_d manual__2024-07-19T18:13:05.641856+00:00 [running]> on host 04b0ec8dd5cd
[2024-07-19T18:13:20.353+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sfakhrutdinov' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='md_currency_d' AIRFLOW_CTX_EXECUTION_DATE='2024-07-19T18:13:05.641856+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-19T18:13:05.641856+00:00'
[2024-07-19T18:13:20.384+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-19T18:13:20.482+0000] {base.py:84} INFO - Using connection ID 'postgres-db' for task execution.
[2024-07-19T18:13:20.668+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-19T18:13:20.693+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-19T18:13:20.768+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=md_currency_d, run_id=manual__2024-07-19T18:13:05.641856+00:00, execution_date=20240719T181305, start_date=20240719T181319, end_date=20240719T181320
[2024-07-19T18:13:20.903+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-19T18:13:21.120+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-19T18:13:21.126+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
