[2024-07-19T18:07:12.662+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-19T18:07:12.828+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.md_ledger_account_s manual__2024-07-19T18:06:55.309501+00:00 [queued]>
[2024-07-19T18:07:12.883+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.md_ledger_account_s manual__2024-07-19T18:06:55.309501+00:00 [queued]>
[2024-07-19T18:07:12.885+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-07-19T18:07:12.975+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): md_ledger_account_s> on 2024-07-19 18:06:55.309501+00:00
[2024-07-19T18:07:12.989+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=3726) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-19T18:07:12.994+0000] {standard_task_runner.py:64} INFO - Started process 3741 to run task
[2024-07-19T18:07:12.994+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'md_ledger_account_s', 'manual__2024-07-19T18:06:55.309501+00:00', '--job-id', '362', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpwfj9luvb']
[2024-07-19T18:07:13.001+0000] {standard_task_runner.py:91} INFO - Job 362: Subtask md_ledger_account_s
[2024-07-19T18:07:13.222+0000] {task_command.py:426} INFO - Running <TaskInstance: insert_data.md_ledger_account_s manual__2024-07-19T18:06:55.309501+00:00 [running]> on host 04b0ec8dd5cd
[2024-07-19T18:07:14.339+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sfakhrutdinov' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='md_ledger_account_s' AIRFLOW_CTX_EXECUTION_DATE='2024-07-19T18:06:55.309501+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-19T18:06:55.309501+00:00'
[2024-07-19T18:07:14.373+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-19T18:07:14.603+0000] {base.py:84} INFO - Using connection ID 'postgres-db' for task execution.
[2024-07-19T18:07:15.046+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-19T18:07:15.057+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.UndefinedColumn: column "CHAPTER" of relation "md_ledger_account_s" does not exist
LINE 1: INSERT INTO ds.md_ledger_account_s ("CHAPTER", "CHAPTER_NAME...
                                            ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/insert_data.py", line 13, in insert_data
    df.to_sql(table_name, engine, schema="ds", if_exists="append", index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3008, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1958, in to_sql
    total_inserted = sql_engine.insert_records(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1507, in insert_records
    raise err
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1498, in insert_records
    return table.insert(chunksize=chunksize, method=method)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1059, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 951, in _execute_insert
    result = conn.execute(self.table.insert(), data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "CHAPTER" of relation "md_ledger_account_s" does not exist
LINE 1: INSERT INTO ds.md_ledger_account_s ("CHAPTER", "CHAPTER_NAME...
                                            ^

[SQL: INSERT INTO ds.md_ledger_account_s ("CHAPTER", "CHAPTER_NAME", "SECTION_NUMBER", "SECTION_NAME", "SUBSECTION_NAME", "LEDGER1_ACCOUNT", "LEDGER1_ACCOUNT_NAME", "LEDGER_ACCOUNT", "LEDGER_ACCOUNT_NAME", "CHARACTERISTIC", "START_DATE", "END_DATE") VALUES (%(CHAPTER)s, %(CHAPTER_NAME)s, %(SECTION_NUMBER)s, %(SECTION_NAME)s, %(SUBSECTION_NAME)s, %(LEDGER1_ACCOUNT)s, %(LEDGER1_ACCOUNT_NAME)s, %(LEDGER_ACCOUNT)s, %(LEDGER_ACCOUNT_NAME)s, %(CHARACTERISTIC)s, %(START_DATE)s, %(END_DATE)s)]
[parameters: ({'CHAPTER': 'А', 'CHAPTER_NAME': 'Балансовые счета', 'SECTION_NUMBER': 3, 'SECTION_NAME': 'МЕЖБАНКОВСКИЕ ОПЕРАЦИИ', 'SUBSECTION_NAME': 'МЕЖБАНКОВСКИЕ РАСЧЕТЫ', 'LEDGER1_ACCOUNT': 302, 'LEDGER1_ACCOUNT_NAME': 'Счета кредитных организаций по другим операциям', 'LEDGER_ACCOUNT': 30204, 'LEDGER_ACCOUNT_NAME': 'Обязательные резервы кредитных организаций по счетам в иностранной валюте, депонированные в Банке России', 'CHARACTERISTIC': 'А', 'START_DATE': '2014-01-01', 'END_DATE': '2050-12-31'}, {'CHAPTER': 'А', 'CHAPTER_NAME': 'Балансовые счета', 'SECTION_NUMBER': 3, 'SECTION_NAME': 'МЕЖБАНКОВСКИЕ ОПЕРАЦИИ', 'SUBSECTION_NAME': 'МЕЖБАНКОВСКИЕ РАСЧЕТЫ', 'LEDGER1_ACCOUNT': 301, 'LEDGER1_ACCOUNT_NAME': 'Корреспондентские счета', 'LEDGER_ACCOUNT': 30109, 'LEDGER_ACCOUNT_NAME': 'Корреспондентские счета кредитных организаций - корреспондентов', 'CHARACTERISTIC': 'П', 'START_DATE': '2008-01-01', 'END_DATE': '2050-12-31'}, {'CHAPTER': 'А', 'CHAPTER_NAME': 'Балансовые счета', 'SECTION_NUMBER': 3, 'SECTION_NAME': 'МЕЖБАНКОВСКИЕ ОПЕРАЦИИ', 'SUBSECTION_NAME': 'МЕЖБАНКОВСКИЕ РАСЧЕТЫ', 'LEDGER1_ACCOUNT': 301, 'LEDGER1_ACCOUNT_NAME': 'Корреспондентские счета', 'LEDGER_ACCOUNT': 30110, 'LEDGER_ACCOUNT_NAME': 'Корреспондентские счета в кредитных организациях - корреспондентах', 'CHARACTERISTIC': 'А', 'START_DATE': '2008-01-01', 'END_DATE': '2050-12-31'}, {'CHAPTER': 'А', 'CHAPTER_NAME': 'Балансовые счета', 'SECTION_NUMBER': 3, 'SECTION_NAME': 'МЕЖБАНКОВСКИЕ ОПЕРАЦИИ', 'SUBSECTION_NAME': 'МЕЖБАНКОВСКИЕ РАСЧЕТЫ', 'LEDGER1_ACCOUNT': 301, 'LEDGER1_ACCOUNT_NAME': 'Корреспондентские счета', 'LEDGER_ACCOUNT': 30111, 'LEDGER_ACCOUNT_NAME': 'Корреспондентские счета банков- нерезидентов', 'CHARACTERISTIC': 'П', 'START_DATE': '2008-01-01', 'END_DATE': '2050-12-31'}, {'CHAPTER': 'А', 'CHAPTER_NAME': 'Балансовые счета', 'SECTION_NUMBER': 3, 'SECTION_NAME': 'МЕЖБАНКОВСКИЕ ОПЕРАЦИИ', 'SUBSECTION_NAME': 'МЕЖБАНКОВСКИЕ РАСЧЕТЫ', 'LEDGER1_ACCOUNT': 301, 'LEDGER1_ACCOUNT_NAME': 'Корреспондентские счета', 'LEDGER_ACCOUNT': 30126, 'LEDGER_ACCOUNT_NAME': 'Резервы на возможные потери', 'CHARACTERISTIC': 'П', 'START_DATE': '2008-01-01', 'END_DATE': '2050-12-31'}, {'CHAPTER': 'А', 'CHAPTER_NAME': 'Балансовые счета', 'SECTION_NUMBER': 3, 'SECTION_NAME': 'МЕЖБАНКОВСКИЕ ОПЕРАЦИИ', 'SUBSECTION_NAME': 'МЕЖБАНКОВСКИЕ РАСЧЕТЫ', 'LEDGER1_ACCOUNT': 302, 'LEDGER1_ACCOUNT_NAME': 'Счета кредитных организаций по другим операциям', 'LEDGER_ACCOUNT': 30223, 'LEDGER_ACCOUNT_NAME': 'Незавершенные переводы и расчеты по банковским счетам клиентов при осуществлении расчетов через подразделения Банка России ', 'CHARACTERISTIC': 'П', 'START_DATE': '2008-01-01', 'END_DATE': '2050-12-31'}, {'CHAPTER': 'А', 'CHAPTER_NAME': 'Балансовые счета', 'SECTION_NUMBER': 3, 'SECTION_NAME': 'МЕЖБАНКОВСКИЕ ОПЕРАЦИИ', 'SUBSECTION_NAME': 'МЕЖБАНКОВСКИЕ РАСЧЕТЫ', 'LEDGER1_ACCOUNT': 302, 'LEDGER1_ACCOUNT_NAME': 'Счета кредитных организаций по другим операциям', 'LEDGER_ACCOUNT': 30236, 'LEDGER_ACCOUNT_NAME': 'Незавершенные переводы, поступившие от платежных систем и на корреспондентские счета ', 'CHARACTERISTIC': 'П', 'START_DATE': '2013-01-01', 'END_DATE': '2050-12-31'}, {'CHAPTER': 'А', 'CHAPTER_NAME': 'Балансовые счета', 'SECTION_NUMBER': 3, 'SECTION_NAME': 'МЕЖБАНКОВСКИЕ ОПЕРАЦИИ', 'SUBSECTION_NAME': 'МЕЖБАНКОВСКИЕ РАСЧЕТЫ', 'LEDGER1_ACCOUNT': 304, 'LEDGER1_ACCOUNT_NAME': 'Счета для осуществления клиринга', 'LEDGER_ACCOUNT': 30413, 'LEDGER_ACCOUNT_NAME': 'Средства на торговых банковских счетах', 'CHARACTERISTIC': 'А', 'START_DATE': '2013-01-01', 'END_DATE': '2050-12-31'}  ... displaying 10 of 18 total bound parameter sets ...  {'CHAPTER': 'А', 'CHAPTER_NAME': 'Балансовые счета', 'SECTION_NUMBER': 3, 'SECTION_NAME': 'МЕЖБАНКОВСКИЕ ОПЕРАЦИИ', 'SUBSECTION_NAME': 'МЕЖБАНКОВСКИЕ РАСЧЕТЫ', 'LEDGER1_ACCOUNT': 302, 'LEDGER1_ACCOUNT_NAME': 'Счета кредитных организаций по другим операциям', 'LEDGER_ACCOUNT': 30202, 'LEDGER_ACCOUNT_NAME': 'Обязательные резервы кредитных организаций по счетам в валюте Российской Федерации, депонированные в Банке России', 'CHARACTERISTIC': 'А', 'START_DATE': '2014-01-01', 'END_DATE': '2050-12-31'}, {'CHAPTER': 'А', 'CHAPTER_NAME': 'Балансовые счета', 'SECTION_NUMBER': 3, 'SECTION_NAME': 'МЕЖБАНКОВСКИЕ ОПЕРАЦИИ', 'SUBSECTION_NAME': 'МЕЖБАНКОВСКИЕ РАСЧЕТЫ', 'LEDGER1_ACCOUNT': 302, 'LEDGER1_ACCOUNT_NAME': 'Счета кредитных организаций по другим операциям', 'LEDGER_ACCOUNT': 30233, 'LEDGER_ACCOUNT_NAME': 'Незавершенные расчеты с операторами услуг платежной инфраструктуры и операторами по переводу денежных средств', 'CHARACTERISTIC': 'А', 'START_DATE': '2014-01-01', 'END_DATE': '2050-12-31'})]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2024-07-19T18:07:15.194+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=insert_data, task_id=md_ledger_account_s, run_id=manual__2024-07-19T18:06:55.309501+00:00, execution_date=20240719T180655, start_date=20240719T180712, end_date=20240719T180715
[2024-07-19T18:07:15.261+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 362 for task md_ledger_account_s ((psycopg2.errors.UndefinedColumn) column "CHAPTER" of relation "md_ledger_account_s" does not exist
LINE 1: INSERT INTO ds.md_ledger_account_s ("CHAPTER", "CHAPTER_NAME...
                                            ^

[SQL: INSERT INTO ds.md_ledger_account_s ("CHAPTER", "CHAPTER_NAME", "SECTION_NUMBER", "SECTION_NAME", "SUBSECTION_NAME", "LEDGER1_ACCOUNT", "LEDGER1_ACCOUNT_NAME", "LEDGER_ACCOUNT", "LEDGER_ACCOUNT_NAME", "CHARACTERISTIC", "START_DATE", "END_DATE") VALUES (%(CHAPTER)s, %(CHAPTER_NAME)s, %(SECTION_NUMBER)s, %(SECTION_NAME)s, %(SUBSECTION_NAME)s, %(LEDGER1_ACCOUNT)s, %(LEDGER1_ACCOUNT_NAME)s, %(LEDGER_ACCOUNT)s, %(LEDGER_ACCOUNT_NAME)s, %(CHARACTERISTIC)s, %(START_DATE)s, %(END_DATE)s)]
[parameters: ({'CHAPTER': 'А', 'CHAPTER_NAME': 'Балансовые счета', 'SECTION_NUMBER': 3, 'SECTION_NAME': 'МЕЖБАНКОВСКИЕ ОПЕРАЦИИ', 'SUBSECTION_NAME': 'МЕЖБАНКОВСКИЕ РАСЧЕТЫ', 'LEDGER1_ACCOUNT': 302, 'LEDGER1_ACCOUNT_NAME': 'Счета кредитных организаций по другим операциям', 'LEDGER_ACCOUNT': 30204, 'LEDGER_ACCOUNT_NAME': 'Обязательные резервы кредитных организаций по счетам в иностранной валюте, депонированные в Банке России', 'CHARACTERISTIC': 'А', 'START_DATE': '2014-01-01', 'END_DATE': '2050-12-31'}, {'CHAPTER': 'А', 'CHAPTER_NAME': 'Балансовые счета', 'SECTION_NUMBER': 3, 'SECTION_NAME': 'МЕЖБАНКОВСКИЕ ОПЕРАЦИИ', 'SUBSECTION_NAME': 'МЕЖБАНКОВСКИЕ РАСЧЕТЫ', 'LEDGER1_ACCOUNT': 301, 'LEDGER1_ACCOUNT_NAME': 'Корреспондентские счета', 'LEDGER_ACCOUNT': 30109, 'LEDGER_ACCOUNT_NAME': 'Корреспондентские счета кредитных организаций - корреспондентов', 'CHARACTERISTIC': 'П', 'START_DATE': '2008-01-01', 'END_DATE': '2050-12-31'}, {'CHAPTER': 'А', 'CHAPTER_NAME': 'Балансовые счета', 'SECTION_NUMBER': 3, 'SECTION_NAME': 'МЕЖБАНКОВСКИЕ ОПЕРАЦИИ', 'SUBSECTION_NAME': 'МЕЖБАНКОВСКИЕ РАСЧЕТЫ', 'LEDGER1_ACCOUNT': 301, 'LEDGER1_ACCOUNT_NAME': 'Корреспондентские счета', 'LEDGER_ACCOUNT': 30110, 'LEDGER_ACCOUNT_NAME': 'Корреспондентские счета в кредитных организациях - корреспондентах', 'CHARACTERISTIC': 'А', 'START_DATE': '2008-01-01', 'END_DATE': '2050-12-31'}, {'CHAPTER': 'А', 'CHAPTER_NAME': 'Балансовые счета', 'SECTION_NUMBER': 3, 'SECTION_NAME': 'МЕЖБАНКОВСКИЕ ОПЕРАЦИИ', 'SUBSECTION_NAME': 'МЕЖБАНКОВСКИЕ РАСЧЕТЫ', 'LEDGER1_ACCOUNT': 301, 'LEDGER1_ACCOUNT_NAME': 'Корреспондентские счета', 'LEDGER_ACCOUNT': 30111, 'LEDGER_ACCOUNT_NAME': 'Корреспондентские счета банков- нерезидентов', 'CHARACTERISTIC': 'П', 'START_DATE': '2008-01-01', 'END_DATE': '2050-12-31'}, {'CHAPTER': 'А', 'CHAPTER_NAME': 'Балансовые счета', 'SECTION_NUMBER': 3, 'SECTION_NAME': 'МЕЖБАНКОВСКИЕ ОПЕРАЦИИ', 'SUBSECTION_NAME': 'МЕЖБАНКОВСКИЕ РАСЧЕТЫ', 'LEDGER1_ACCOUNT': 301, 'LEDGER1_ACCOUNT_NAME': 'Корреспондентские счета', 'LEDGER_ACCOUNT': 30126, 'LEDGER_ACCOUNT_NAME': 'Резервы на возможные потери', 'CHARACTERISTIC': 'П', 'START_DATE': '2008-01-01', 'END_DATE': '2050-12-31'}, {'CHAPTER': 'А', 'CHAPTER_NAME': 'Балансовые счета', 'SECTION_NUMBER': 3, 'SECTION_NAME': 'МЕЖБАНКОВСКИЕ ОПЕРАЦИИ', 'SUBSECTION_NAME': 'МЕЖБАНКОВСКИЕ РАСЧЕТЫ', 'LEDGER1_ACCOUNT': 302, 'LEDGER1_ACCOUNT_NAME': 'Счета кредитных организаций по другим операциям', 'LEDGER_ACCOUNT': 30223, 'LEDGER_ACCOUNT_NAME': 'Незавершенные переводы и расчеты по банковским счетам клиентов при осуществлении расчетов через подразделения Банка России ', 'CHARACTERISTIC': 'П', 'START_DATE': '2008-01-01', 'END_DATE': '2050-12-31'}, {'CHAPTER': 'А', 'CHAPTER_NAME': 'Балансовые счета', 'SECTION_NUMBER': 3, 'SECTION_NAME': 'МЕЖБАНКОВСКИЕ ОПЕРАЦИИ', 'SUBSECTION_NAME': 'МЕЖБАНКОВСКИЕ РАСЧЕТЫ', 'LEDGER1_ACCOUNT': 302, 'LEDGER1_ACCOUNT_NAME': 'Счета кредитных организаций по другим операциям', 'LEDGER_ACCOUNT': 30236, 'LEDGER_ACCOUNT_NAME': 'Незавершенные переводы, поступившие от платежных систем и на корреспондентские счета ', 'CHARACTERISTIC': 'П', 'START_DATE': '2013-01-01', 'END_DATE': '2050-12-31'}, {'CHAPTER': 'А', 'CHAPTER_NAME': 'Балансовые счета', 'SECTION_NUMBER': 3, 'SECTION_NAME': 'МЕЖБАНКОВСКИЕ ОПЕРАЦИИ', 'SUBSECTION_NAME': 'МЕЖБАНКОВСКИЕ РАСЧЕТЫ', 'LEDGER1_ACCOUNT': 304, 'LEDGER1_ACCOUNT_NAME': 'Счета для осуществления клиринга', 'LEDGER_ACCOUNT': 30413, 'LEDGER_ACCOUNT_NAME': 'Средства на торговых банковских счетах', 'CHARACTERISTIC': 'А', 'START_DATE': '2013-01-01', 'END_DATE': '2050-12-31'}  ... displaying 10 of 18 total bound parameter sets ...  {'CHAPTER': 'А', 'CHAPTER_NAME': 'Балансовые счета', 'SECTION_NUMBER': 3, 'SECTION_NAME': 'МЕЖБАНКОВСКИЕ ОПЕРАЦИИ', 'SUBSECTION_NAME': 'МЕЖБАНКОВСКИЕ РАСЧЕТЫ', 'LEDGER1_ACCOUNT': 302, 'LEDGER1_ACCOUNT_NAME': 'Счета кредитных организаций по другим операциям', 'LEDGER_ACCOUNT': 30202, 'LEDGER_ACCOUNT_NAME': 'Обязательные резервы кредитных организаций по счетам в валюте Российской Федерации, депонированные в Банке России', 'CHARACTERISTIC': 'А', 'START_DATE': '2014-01-01', 'END_DATE': '2050-12-31'}, {'CHAPTER': 'А', 'CHAPTER_NAME': 'Балансовые счета', 'SECTION_NUMBER': 3, 'SECTION_NAME': 'МЕЖБАНКОВСКИЕ ОПЕРАЦИИ', 'SUBSECTION_NAME': 'МЕЖБАНКОВСКИЕ РАСЧЕТЫ', 'LEDGER1_ACCOUNT': 302, 'LEDGER1_ACCOUNT_NAME': 'Счета кредитных организаций по другим операциям', 'LEDGER_ACCOUNT': 30233, 'LEDGER_ACCOUNT_NAME': 'Незавершенные расчеты с операторами услуг платежной инфраструктуры и операторами по переводу денежных средств', 'CHARACTERISTIC': 'А', 'START_DATE': '2014-01-01', 'END_DATE': '2050-12-31'})]
(Background on this error at: https://sqlalche.me/e/14/f405); 3741)
[2024-07-19T18:07:15.332+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-19T18:07:15.461+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-19T18:07:15.463+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
