[2024-07-19T16:56:05.130+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-19T16:56:05.345+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.md_account_d manual__2024-07-19T16:55:54.396947+00:00 [queued]>
[2024-07-19T16:56:05.417+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.md_account_d manual__2024-07-19T16:55:54.396947+00:00 [queued]>
[2024-07-19T16:56:05.421+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-07-19T16:56:05.476+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): md_account_d> on 2024-07-19 16:55:54.396947+00:00
[2024-07-19T16:56:05.497+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=2785) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-19T16:56:05.508+0000] {standard_task_runner.py:64} INFO - Started process 2800 to run task
[2024-07-19T16:56:05.528+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'md_account_d', 'manual__2024-07-19T16:55:54.396947+00:00', '--job-id', '357', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpyyz5eihr']
[2024-07-19T16:56:05.534+0000] {standard_task_runner.py:91} INFO - Job 357: Subtask md_account_d
[2024-07-19T16:56:05.643+0000] {task_command.py:426} INFO - Running <TaskInstance: insert_data.md_account_d manual__2024-07-19T16:55:54.396947+00:00 [running]> on host 04b0ec8dd5cd
[2024-07-19T16:56:05.917+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sfakhrutdinov' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='md_account_d' AIRFLOW_CTX_EXECUTION_DATE='2024-07-19T16:55:54.396947+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-19T16:55:54.396947+00:00'
[2024-07-19T16:56:05.931+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-19T16:56:06.006+0000] {base.py:84} INFO - Using connection ID 'postgres-db' for task execution.
[2024-07-19T16:56:06.088+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-19T16:56:06.099+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-19T16:56:06.127+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=md_account_d, run_id=manual__2024-07-19T16:55:54.396947+00:00, execution_date=20240719T165554, start_date=20240719T165605, end_date=20240719T165606
[2024-07-19T16:56:06.197+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-19T16:56:06.312+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-19T16:56:06.317+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
