[2024-07-19T18:13:20.966+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-19T18:13:21.146+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.ft_balance_f manual__2024-07-19T18:13:05.641856+00:00 [queued]>
[2024-07-19T18:13:21.173+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.ft_balance_f manual__2024-07-19T18:13:05.641856+00:00 [queued]>
[2024-07-19T18:13:21.174+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-07-19T18:13:21.237+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): ft_balance_f> on 2024-07-19 18:13:05.641856+00:00
[2024-07-19T18:13:21.282+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=3821) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-19T18:13:21.299+0000] {standard_task_runner.py:64} INFO - Started process 3845 to run task
[2024-07-19T18:13:21.296+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'ft_balance_f', 'manual__2024-07-19T18:13:05.641856+00:00', '--job-id', '370', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpg60oi248']
[2024-07-19T18:13:21.303+0000] {standard_task_runner.py:91} INFO - Job 370: Subtask ft_balance_f
[2024-07-19T18:13:21.426+0000] {task_command.py:426} INFO - Running <TaskInstance: insert_data.ft_balance_f manual__2024-07-19T18:13:05.641856+00:00 [running]> on host 04b0ec8dd5cd
[2024-07-19T18:13:21.584+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sfakhrutdinov' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='ft_balance_f' AIRFLOW_CTX_EXECUTION_DATE='2024-07-19T18:13:05.641856+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-19T18:13:05.641856+00:00'
[2024-07-19T18:13:21.587+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-19T18:13:21.616+0000] {base.py:84} INFO - Using connection ID 'postgres-db' for task execution.
[2024-07-19T18:13:21.696+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-19T18:13:21.699+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-19T18:13:21.707+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=ft_balance_f, run_id=manual__2024-07-19T18:13:05.641856+00:00, execution_date=20240719T181305, start_date=20240719T181321, end_date=20240719T181321
[2024-07-19T18:13:21.736+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-19T18:13:21.754+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-19T18:13:21.755+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
