[2024-07-20T20:09:09.184+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-20T20:09:09.254+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.md_ledger_account_s manual__2024-07-20T20:09:02.099817+00:00 [queued]>
[2024-07-20T20:09:09.279+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.md_ledger_account_s manual__2024-07-20T20:09:02.099817+00:00 [queued]>
[2024-07-20T20:09:09.280+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-07-20T20:09:09.311+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): md_ledger_account_s> on 2024-07-20 20:09:02.099817+00:00
[2024-07-20T20:09:09.372+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=268) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-20T20:09:09.381+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'md_ledger_account_s', 'manual__2024-07-20T20:09:02.099817+00:00', '--job-id', '391', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpw1tqs0vz']
[2024-07-20T20:09:09.385+0000] {standard_task_runner.py:64} INFO - Started process 280 to run task
[2024-07-20T20:09:09.386+0000] {standard_task_runner.py:91} INFO - Job 391: Subtask md_ledger_account_s
[2024-07-20T20:09:09.623+0000] {task_command.py:426} INFO - Running <TaskInstance: insert_data.md_ledger_account_s manual__2024-07-20T20:09:02.099817+00:00 [running]> on host 04b0ec8dd5cd
[2024-07-20T20:09:09.985+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sfakhrutdinov' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='md_ledger_account_s' AIRFLOW_CTX_EXECUTION_DATE='2024-07-20T20:09:02.099817+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-20T20:09:02.099817+00:00'
[2024-07-20T20:09:09.988+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-20T20:09:10.059+0000] {base.py:84} INFO - Using connection ID 'postgres-db' for task execution.
[2024-07-20T20:09:10.467+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-20T20:09:10.474+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-20T20:09:10.513+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=md_ledger_account_s, run_id=manual__2024-07-20T20:09:02.099817+00:00, execution_date=20240720T200902, start_date=20240720T200909, end_date=20240720T200910
[2024-07-20T20:09:10.611+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-20T20:09:10.686+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
