[2024-07-20T19:56:22.707+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-20T19:56:22.944+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.md_ledger_account_s manual__2024-07-20T19:56:06.732377+00:00 [queued]>
[2024-07-20T19:56:23.007+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.md_ledger_account_s manual__2024-07-20T19:56:06.732377+00:00 [queued]>
[2024-07-20T19:56:23.015+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-07-20T19:56:23.123+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): md_ledger_account_s> on 2024-07-20 19:56:06.732377+00:00
[2024-07-20T19:56:23.176+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=85) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-20T19:56:23.190+0000] {standard_task_runner.py:64} INFO - Started process 105 to run task
[2024-07-20T19:56:23.186+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'md_ledger_account_s', 'manual__2024-07-20T19:56:06.732377+00:00', '--job-id', '388', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpnz89d431']
[2024-07-20T19:56:23.195+0000] {standard_task_runner.py:91} INFO - Job 388: Subtask md_ledger_account_s
[2024-07-20T19:56:23.797+0000] {task_command.py:426} INFO - Running <TaskInstance: insert_data.md_ledger_account_s manual__2024-07-20T19:56:06.732377+00:00 [running]> on host 04b0ec8dd5cd
[2024-07-20T19:56:24.511+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sfakhrutdinov' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='md_ledger_account_s' AIRFLOW_CTX_EXECUTION_DATE='2024-07-20T19:56:06.732377+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-20T19:56:06.732377+00:00'
[2024-07-20T19:56:24.557+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-20T19:56:24.896+0000] {base.py:84} INFO - Using connection ID 'postgres-db' for task execution.
[2024-07-20T19:56:25.394+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-07-20T19:56:25.460+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-20T19:56:25.588+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=md_ledger_account_s, run_id=manual__2024-07-20T19:56:06.732377+00:00, execution_date=20240720T195606, start_date=20240720T195622, end_date=20240720T195625
[2024-07-20T19:56:25.848+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-20T19:56:26.207+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-20T19:56:26.213+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
